name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'tyrchen/smithy-docker'
          file: 'assets.tar.gz'
      - name: extract assets to $HOME/.m2
        run: |
          rm -rf $HOME/.m2
          tar -xzf assets.tar.gz -C $HOME --strip-components=2
          ls -la $HOME/.m2
          rm assets.tar.gz
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install Smithy
        run: |
          mkdir -p /tmp/smithy
          curl -L https://github.com/smithy-lang/smithy/releases/download/1.41.1/smithy-cli-linux-x86_64.tar.gz -o /tmp/smithy-cli-linux.tar.gz
          tar xvzf /tmp/smithy-cli-linux.tar.gz -C /tmp/smithy
          sudo /tmp/smithy/install
      - name: Go to repo and run smithy build
        run: |
          cd $GITHUB_WORKSPACE/smithy && smithy build
      - name: Got to repo and copy generated files
        run: |
          mkdir -p $GITHUB_WORKSPACE/smithy/gen
          cd $GITHUB_WORKSPACE/smithy
          cp -r build/smithy/source/openapi gen/openapi
          cp -r build/smithy/source/python-client-codegen gen/python-client-sdk
          cp -r build/smithy/source/rust-client-codegen gen/rust-client-sdk
          cp -r build/smithy/source/typescript-client-codegen gen/typescript-client-sdk
          cp -r build/smithy/source/swift-codegen gen/swift-client-sdk
          cp -r build/smithy/source/rust-server-codegen gen/rust-server-sdk
      - name: Commit generated files
        run: |
          cd $GITHUB_WORKSPACE
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "[skip ci] Update generated files"
      - name: Push generated files
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
